{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "addi-workload.fullname" . }}
  namespace: {{ include "addi-workload.namespace" . }}
  labels:
    {{- include "addi-workload.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if and (eq .Values.workloadType "api") (ne .Values.rollout.strategy "rolling") }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "addi-workload.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
{{- end }}
