{{- if and (eq .Values.workloadType "api") (eq .Values.rollout.strategy "canary") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "addi-workload.fullname" . }}-canary
  namespace: {{ include "addi-workload.namespace" . }}
  labels:
    {{- include "addi-workload.labels" . | nindent 4 }}
    app.kubernetes.io/component: canary
spec:
  type: ClusterIP
  selector:
    {{- include "addi-workload.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
{{- end }}
